### ISSUE TITLE
comments on bonus optimizing speed

### ISSUE THREAD

**Issue by MalikaIhle** [MalikaIhle/Simulations-for-Advanced-Power-Analyses#10]
make the notification disappear: 
'Lade nötiges Paket: future'
(was confused by the german in the middle of this)

**Comment by MalikaIhle** [comment]
call out note: 'To improve the benefits of parallel processing, make sure that each single parallel process runs as long (i.e., in an uninterrupted way) as possible.'

by doing what?

**Comment by MalikaIhle** [comment]
there is still a TODO in the recap:
"Avoid unnecessary computations and/or switch to optimized packages that do the same computations much faster. Solution: TODO (Rfast)"

**Comment by MalikaIhle** [comment]
> > make the notification disappear: 'Lade nötiges Paket: future'
> 
> You can do this by adding `#| output: false` on top of the code chunk

done

**Comment by nicebread** [comment]
All done.
