### ISSUE TITLE
comments on bonus how many iterations

### ISSUE THREAD

**Issue by MalikaIhle** [MalikaIhle/Simulations-for-Advanced-Power-Analyses#12]
the top of the page still has my #FIXME:

#FIXME I couldn’t jump right into this page and understand what is iteration, repetition and n were. one or two lines could be added at the top, something like:

To find the sample size needed for a study, we have previsouly use e.g. 1000 iterations of data simulation and analysis, and varied the sample size from e.g. 100 to 1000, every 50, to find where the e.g. 80% power threshold was crossed (see e.g. https://shiny.psy.lmu.de/r-tutorials/powersim/LM.html#sample-size-planning-find-the-necessary-sample-size #FIXME relative link). But is 1000 iterations giving a precise enough result?

**Comment by MalikaIhle** [comment]
perhaps some blue note can be added here at the top:

"Using the [optimized code](https://malikaihle.github.io/Simulations-for-Advanced-Power-Analyses/optimizing_code.html), we can explore how many Monte-Carlo iterations are necessary to get stable computational results: we can re-run the same simulation with the same sample size!"

 BLUE NOTE

"Let’s start with 1000 iterations (at n = 100, and 10 repetitions of the same power analysis):"

with a wikipedia definition of monte carlo:

"Monte Carlo methods, or Monte Carlo experiments, are a broad class of computational algorithms that rely on repeated random sampling to obtain numerical results. The underlying concept is to use randomness to solve problems that might be deterministic in principle. They are often used in physical and mathematical problems and are most useful when it is difficult or impossible to use other approaches. Monte Carlo methods are mainly used in three problem classes: optimization, numerical integration, and generating draws from a probability distribution.

**Comment by nicebread** [comment]
Done.
