### ISSUE TITLE
comments on resources

### ISSUE THREAD

**Issue by MalikaIhle** [MalikaIhle/Simulations-for-Advanced-Power-Analyses#13]
currently:

"
https://julianquandt.com/post/power-analysis-by-data-simulation-in-r-part-i/ (see Parts I to IV)
“Simulation-based power analysis for regression” by Andrew Hales ([Youtube video](https://www.youtube.com/watch?v=x2hhc5KYw-c), [OSF Material](https://osf.io/e42mg/))
"

maybe add a line description about why the resource is useful (in comparison to the current material)

**Comment by nicebread** [comment]
Done.
