### ISSUE TITLE
comments on SEM

### ISSUE THREAD

**Issue by MalikaIhle** [MalikaIhle/Simulations-for-Advanced-Power-Analyses#15]
mention of a bonus page that doesn't exist yet, at the very top:
"Please see the bonus chapter titled “XXX” if you’re interested in power analyses for fit indices."

**Comment by MalikaIhle** [comment]
spell out RMSEA [R.. M... ...] ?

**Comment by MalikaIhle** [comment]
line 32: as we will use this workshop for non psychology students in the future, jsut specify the terms that are psychology specific. e.g. the big 5 -> the big 5 personality traits 

Let’s consider the following example: We are planning to conduct a study investigating whether **people's** openness to experience (as conceptualized in the big five **personality traits**) relates negatively to generalized prejudice, that is a latent variable comprising prejudice towards different social groups (e.g., women, foreigners, homosexuals, disabled people).

**Comment by MalikaIhle** [comment]
line 63: DP is a continuous variable measuring prejudice toward mentally people with disabilities.

--> toward people with disabilities? or 
--> toward people with mental disabilities?

**Comment by MalikaIhle** [comment]
Bergh keeps being attached and detached - can't it stay attached? otherwise I'm not sure it's less distracting that specifying the dataset name each time?

**Comment by MalikaIhle** [comment]
line 77: "With these population parameters, we can then simulate data, for example using the mrvnorm function from the MASS package"

I don't see this function being used later on so I'm a bit confused. is it a possibility (but not used here) or is it used here (but didn't see it)?

**Comment by nicebread** [comment]
> line 77: "With these population parameters, we can then simulate data, for example using the mrvnorm function from the MASS package"

I use the `rmvnorm` function from the Rfast package (because it is faster) - maybe we should converge on this one?

**Comment by MalikaIhle** [comment]
line 169: # TODO: How can we enter standardized regression coefficients?
to resolve

**Comment by MalikaIhle** [comment]
line 321: The next step is to ~~simply~~ integrate this code into our first simulation-based power analysis in this chapter, that is, to replace the data simulation process using **XX** with this new method using simulateData() from the lavaan package.

XX to resolve

**Comment by MalikaIhle** [comment]
line 366: need a conclusion after graph to describe what should be noticed?

**Comment by MalikaIhle** [comment]
line 375 "In the following two sub-paragraphs, we would like to present two alternatives and/or extensions to this first way of doing a power analysis for a SEM. First, we would like to show how we can use a “smallest effect size of interest” (SESOI) instead of an expected effect size. Second, we would like to present an alternative way to simulate data for SEMs, simply by using a built-in function in the lavaan package."

--> it seems the first paragraph is about simulating with Laavan, reverse the order in the previous sentence?
--> the secodn paragraph is called 'A simulation-based power analysis for a mediation model with latent variables' so maybe not about SESOI?

**Comment by MalikaIhle** [comment]
trying to make line 375 shorter: 
"Sometimes, researchers not only wish to investigate whether and how two (latent) variables related to each other, but rather whether the association between two (manifest or latent) variables is mediated by a third variable. We will run a power analysis for such a latent mediation model in the following. To this end, we assume that we were interested in whether a potential effect of gender on generalized prejudice is (fully or partially) mediated by openness to experience. Fortunately, the data set by Bergh et al (2016) also contains a gender variable. We can therefore repeat the same steps as in our previous power analysis, but only incorporate gender into our analysis. Specifically, this means that we will follow these steps:"

maybe:

Sometimes, researchers not only wish to investigate whether and how two (latent) variables related to each other, but also whether the association between two (manifest or latent) variables is mediated by a third variable. We will run a power analysis for such a latent mediation model, investigating whether gender affects generalized prejudice, (fully or partially) mediated by openness to experience, with the Bergh et al (2016) dataset. We can repeat the same steps as in our previous power analysis, while incorporating gender into our analysis. Specifically, we will follow these steps:

--> need to check my version is correct in the following two poitns:
- in english, it would be  'Not only',... "but also" or 'do not wish to investigate X but rather Y'. I changed to the former but maybe the analyses doesn't allow to analyse both at the same time
- " whether gender affects generalized prejudice, (fully or partially) mediated by openness to experience" I don't know if this is a correct way to describe a nmediation model (since I don't know what they are really)

**Comment by MalikaIhle** [comment]
I think I would remove 'SEM" from the title because it goes on two lines like it is, and for consistency with the other title where we removed the acronym
