### ISSUE TITLE
SEM comments

### ISSUE THREAD

**Issue by nicebread** [MalikaIhle/Simulations-for-Advanced-Power-Analyses#17]
- there is a line break in the `apaTables::apa.cor.table(cbind(EP, SP, HP, DP, O1, O2, O3))` - can you make the font smaller in that chunk?

Otherwise it looks good!

**Comment by fischer-mo** [comment]
This one was difficult, because the chunk option "out.width" unexpectetly didnt work here. I found another work-around...
