### ISSUE TITLE
Ensure consistent language and variable naming

### ISSUE THREAD

**Issue by nicebread** [MalikaIhle/Simulations-for-Advanced-Power-Analyses#2]
* `iterations`: Repetitions in Monte Carlo simulation
* `SESOI`: not "minimal clinically important difference" or other terms

**Comment by MalikaIhle** [comment]
so actually, the name Monte Carlo simulation is never defined in my tutorial, nor in our current material and neither in the intro https://aaroncaldwell.us/SuperpowerBook/introduction-to-power-analysis.html we will link to. I think this should be defined somewhere if we want to use this specific term. 

Gathered on wikipedia:

Monte Carlo methods, or Monte Carlo experiments, are a broad class of computational algorithms that rely on repeated random sampling to obtain numerical results. The underlying concept is to use randomness to solve problems that might be deterministic in principle. They are often used in physical and mathematical problems and are most useful when it is difficult or impossible to use other approaches. Monte Carlo methods are mainly used in three problem classes: optimization, numerical integration, and generating draws from a probability distribution.

**Comment by MalikaIhle** [comment]
I think language is very consistent accross both your pages.
