### ISSUE TITLE
add 'Reading/working time: ~XX min.' to GLM, LMM, SEM

### ISSUE THREAD

**Issue by MalikaIhle** [MalikaIhle/Simulations-for-Advanced-Power-Analyses#8]

**Comment by MalikaIhle** [comment]
GLM: 35 min?

**Comment by nicebread** [comment]
Martin and Gracia are testing these chapters and record the time. But 35 min. seems reasonable.

**Comment by MalikaIhle** [comment]
bonus optimizing for speed: 30 min?

**Comment by MalikaIhle** [comment]
LMM: 45 min?

**Comment by MalikaIhle** [comment]
bonus how many iteration: 25 min?

**Comment by MalikaIhle** [comment]
my time estimates for GLMM, LMM, and bonuses are likely quite underestimated because these are my second read so a lot of brain processing had already been done. These numbers however matches/are proportionate to the estimates already provided (e.g. 50 min for LM1). I would say these are the minimum estimated time.

**Comment by MalikaIhle** [comment]
SEM: 50 min as it is? but missing a section on SESOI? 
also missing bonus section on power analyses for fit indices (though this may be a separate page)
