### ISSUE TITLE
comments on LMM

### ISSUE THREAD

**Issue by MalikaIhle** [MalikaIhle/Simulations-for-Advanced-Power-Analyses#9]
line 50:  Hence, the question for this model is: Is there a trend over time in BDI scores?

is there a **linear** trend?

**Comment by MalikaIhle** [comment]
the equations are baffling to me, and I still wouldn't know how to get the parameter values, but I guess trying to get parameter values is something they can also work on with you in the friday session.

**Comment by nicebread** [comment]
Done - added more information on these questions.

**Comment by MalikaIhle** [comment]
what does 'plan(multisession)' mean at the very top?

**Comment by MalikaIhle** [comment]
> Done - added more information on these questions.

I'm reading this page again because I wasn't finished but don't see your changes - are you able to recompile the webstie? @nicebread

**Comment by nicebread** [comment]
Now re-rendered.

**Comment by MalikaIhle** [comment]
perhaps offer comparison of results of faux package with yours as you did with other apps?

**Comment by nicebread** [comment]
> perhaps offer comparison of results of faux package with yours as you did with other apps?

faux doesn't do directly power analysis- it just simulates the data, and then you put it into a for loop yourself. So I think this makes no real difference. But I added this sentence:

"When you plug this simulation function into our power analysis loop, you will get the same results."
